/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedAccionesRouteImport } from './routes/_authenticated/acciones'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/admin'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedHistorialRouteImport } from './routes/_authenticated/historial'
import { Route as AuthenticatedNormasRouteImport } from './routes/_authenticated/normas'
import { Route as AuthenticatedEvaluacionIdRouteImport } from './routes/_authenticated/evaluacion.$id'
import { Route as AuthenticatedInformeIdRouteImport } from './routes/_authenticated/informe.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAccionesRoute = AuthenticatedAccionesRouteImport.update({
  id: '/acciones',
  path: '/acciones',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedHistorialRoute = AuthenticatedHistorialRouteImport.update({
  id: '/historial',
  path: '/historial',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedNormasRoute = AuthenticatedNormasRouteImport.update({
  id: '/normas',
  path: '/normas',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedEvaluacionIdRoute =
  AuthenticatedEvaluacionIdRouteImport.update({
    id: '/evaluacion/$id',
    path: '/evaluacion/$id',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedInformeIdRoute = AuthenticatedInformeIdRouteImport.update({
  id: '/informe/$id',
  path: '/informe/$id',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/acciones': typeof AuthenticatedAccionesRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/historial': typeof AuthenticatedHistorialRoute
  '/normas': typeof AuthenticatedNormasRoute
  '/evaluacion/$id': typeof AuthenticatedEvaluacionIdRoute
  '/informe/$id': typeof AuthenticatedInformeIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/acciones': typeof AuthenticatedAccionesRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/historial': typeof AuthenticatedHistorialRoute
  '/normas': typeof AuthenticatedNormasRoute
  '/evaluacion/$id': typeof AuthenticatedEvaluacionIdRoute
  '/informe/$id': typeof AuthenticatedInformeIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/_authenticated/acciones': typeof AuthenticatedAccionesRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/historial': typeof AuthenticatedHistorialRoute
  '/_authenticated/normas': typeof AuthenticatedNormasRoute
  '/_authenticated/evaluacion/$id': typeof AuthenticatedEvaluacionIdRoute
  '/_authenticated/informe/$id': typeof AuthenticatedInformeIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/acciones'
    | '/admin'
    | '/dashboard'
    | '/historial'
    | '/normas'
    | '/evaluacion/$id'
    | '/informe/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/acciones'
    | '/admin'
    | '/dashboard'
    | '/historial'
    | '/normas'
    | '/evaluacion/$id'
    | '/informe/$id'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/acciones'
    | '/_authenticated/admin'
    | '/_authenticated/dashboard'
    | '/_authenticated/historial'
    | '/_authenticated/normas'
    | '/_authenticated/evaluacion/$id'
    | '/_authenticated/informe/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/acciones': {
      id: '/_authenticated/acciones'
      path: '/acciones'
      fullPath: '/acciones'
      preLoaderRoute: typeof AuthenticatedAccionesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/historial': {
      id: '/_authenticated/historial'
      path: '/historial'
      fullPath: '/historial'
      preLoaderRoute: typeof AuthenticatedHistorialRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/normas': {
      id: '/_authenticated/normas'
      path: '/normas'
      fullPath: '/normas'
      preLoaderRoute: typeof AuthenticatedNormasRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/evaluacion/$id': {
      id: '/_authenticated/evaluacion/$id'
      path: '/evaluacion/$id'
      fullPath: '/evaluacion/$id'
      preLoaderRoute: typeof AuthenticatedEvaluacionIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/informe/$id': {
      id: '/_authenticated/informe/$id'
      path: '/informe/$id'
      fullPath: '/informe/$id'
      preLoaderRoute: typeof AuthenticatedInformeIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAccionesRoute: typeof AuthenticatedAccionesRoute
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedHistorialRoute: typeof AuthenticatedHistorialRoute
  AuthenticatedNormasRoute: typeof AuthenticatedNormasRoute
  AuthenticatedEvaluacionIdRoute: typeof AuthenticatedEvaluacionIdRoute
  AuthenticatedInformeIdRoute: typeof AuthenticatedInformeIdRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAccionesRoute: AuthenticatedAccionesRoute,
  AuthenticatedAdminRoute: AuthenticatedAdminRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedHistorialRoute: AuthenticatedHistorialRoute,
  AuthenticatedNormasRoute: AuthenticatedNormasRoute,
  AuthenticatedEvaluacionIdRoute: AuthenticatedEvaluacionIdRoute,
  AuthenticatedInformeIdRoute: AuthenticatedInformeIdRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
